// Diccionario de traducciones extendido
const translations = {
    es: {
        langBtn: "EN",
        ingresar: "Ingresar",
        title1: "Renueva y ",
        title2: "limpia tu mente",
        title3: " cada día.",
        desc: "Una app web para luchar contra el pecado memorizando la Palabra cada día.",
        empezar: "Empezar",
        verseText: '"No os conforméis a este siglo, sino transformaos por medio de la renovación de vuestro entendimiento..." <strong class="verse-ref">— Romanos 12:2</strong>',
        attributionText: 'Logo creado por: <a href="https://www.flaticon.es/iconos-gratis/espada" title="espada iconos" target="_blank">FR_Media - Flaticon</a>',
        // Textos del Login
        tabLogin: "Iniciar Sesión",
        tabRegister: "Crear Cuenta",
        lblEmail: "Correo Electrónico",
        lblPass: "Contraseña",
        lblName: "Nombre",
        btnSubmitLogin: "Ingresar",
        btnSubmitReg: "Registrarse",
        // Textos del Dashboard
        dashTitle: 'Áreas de <span class="emphasized">Batalla</span>',
        dashSubtitle: "Selecciona un área para memorizar y renovar tu entendimiento hoy.",
        titleSexual: "Pecado Sexual",
        descSexual: "Guardar el cuerpo y la mente en santidad, huyendo de las pasiones juveniles.",
        titleOrgullo: "Orgullo / Soberbia",
        descOrgullo: "Reconocer la dependencia absoluta de Dios y revestirse de profunda humildad.",
        titleGratitud: "Falta de Gratitud",
        descGratitud: "Combatir la queja permanente desarrollando un corazón agradecido en todo.",
        btnLuchar: "Luchar",
        logout: "Cerrar Sesión"
    },
    en: {
        langBtn: "ES",
        ingresar: "Login",
        title1: "Renew and ",
        title2: "cleanse your mind",
        title3: " every day.",
        desc: "A web app to fight sin by memorizing the Word every day.",
        empezar: "Get Started",
        verseText: '"Do not conform to the pattern of this world, but be transformed by the renewing of your mind..." <strong class="verse-ref">— Romans 12:2</strong>',
        attributionText: 'Logo created by: <a href="https://www.flaticon.es/iconos-gratis/espada" title="espada icons" target="_blank">FR_Media - Flaticon</a>',
        // Login Texts
        tabLogin: "Log In",
        tabRegister: "Sign Up",
        lblEmail: "Email",
        lblPass: "Password",
        lblName: "Name",
        btnSubmitLogin: "Log In",
        btnSubmitReg: "Register",
        // Dashboard Texts
        dashTitle: 'Areas of <span class="emphasized">Battle</span>',
        dashSubtitle: "Select an area to memorize and renew your understanding today.",
        titleSexual: "Sexual Sin",
        descSexual: "Guard the body and mind in holiness, fleeing from youthful passions.",
        titleOrgullo: "Pride / Arrogance",
        descOrgullo: "Recognize absolute dependence on God and clothe yourself with deep humility.",
        titleGratitud: "Lack of Gratitud",
        descGratitud: "Combat permanent complaining by developing a thankful heart in everything.",
        btnLuchar: "Fight",
        logout: "Logout"
    }
};

// 1. Lista de 30 versículos contra el Pecado Sexual
const sexualSinVerses = [
    { ref: "1 Tesalonicenses 4:3", text: "Pues la voluntad de Dios es vuestra santificación; que os apartéis de fornicación." },
    { ref: "1 Tesalonicenses 4:4-5", text: "Que cada uno de vosotros sepa tener su propia esposa en santidad y honor; no en pasión de concupiscencia, como los gentiles que no conocen a Dios." },
    { ref: "1 Corintios 6:18", text: "Huid de la fornicación. Cualquier otro pecado que el hombre cometa, está fuera del cuerpo; mas el que fornica, contra su propio cuerpo peca." },
    { ref: "1 Corintios 6:19-20", text: "¿O ignoráis que vuestro cuerpo es templo del Espíritu Santo, el cual está en vosotros, el cual tenéis de Dios, y que no sois vuestros? Porque habéis sido comprados por precio; glorificad, pues, a Dios en vuestro cuerpo." },
    { ref: "Colosenses 3:5", text: "Haced morir, pues, lo terrenal en vosotros: fornicación, impureza, pasiones desordenadas, malos deseos y avaricia, que es idolatría." },
    { ref: "Efesios 5:3", text: "Pero fornicación y toda impureza, o avaricia, ni aun se nombre entre vosotros, como conviene a santos." },
    { ref: "Mateo 5:28", text: "Pero yo os digo que cualquiera que mira a una mujer para codiciarla, ya adulteró con ella en su corazón." },
    { ref: "2 Timoteo 2:22", text: "Huye también de las pasiones juveniles, y sigue la justicia, la fe, el amor y la paz, con los que de corazón limpio invocan al Señor." },
    { ref: "Salmos 119:9", text: "¿Con qué limpiará el joven su camino? Con guardar tu palabra." },
    { ref: "Proverbios 4:23", text: "Sobre toda cosa guardada, guarda tu corazón; porque de él mana la vida." },
    { ref: "Hebreos 13:4", text: "Honroso sea en todos el matrimonio, y el lecho sin mancilla; pero a los fornicarios y a los adúlteros los juzgará Dios." },
    { ref: "Gálatas 5:16", text: "Digo, pues: Andad en el Espíritu, y no satisfagáis los deseos de la carne." },
    { ref: "1 Pedro 2:11", text: "Amados, yo os ruego como a extranjeros y peregrinos, que os abstengáis de los deseos carnales que batallan contra el alma." },
    { ref: "Romanos 13:14", text: "Sino vestíos del Señor Jesucristo, y no proveáis para los deseos de la carne." },
    { ref: "Filipenses 4:8", text: "Por lo demás, hermanos, todo lo que es verdadero, todo lo honesto, todo lo justo, todo lo puro, todo lo amable, todo lo que es de buen nombre; si hay virtud alguna, si algo digno de alabanza, en esto pensad." },
    { ref: "1 Juan 2:16", text: "Porque todo lo que hay en el mundo, los deseos de la carne, los deseos de los ojos, y la vanagloria de la vida, no proviene del Padre, sino del mundo." },
    { ref: "Santiago 1:14-15", text: "Sino que cada uno es tentado, cuando de su propia concupiscencia es atraído y seducido. Entonces la concupiscencia, después que ha concebido, da a luz el pecado." },
    { ref: "1 Corintios 10:13", text: "No os ha sobrevenido ninguna tentación que no sea humana; pero fiel es Dios, que no os dejará ser tentados más de lo que podéis resistir." },
    { ref: "Salmos 51:10", text: "Crea en mí, oh Dios, un corazón limpio, y renueva un espíritu recto dentro de mí." },
    { ref: "Proverbios 6:25", text: "No codicies su hermosura en tu corazón, ni ella te prenda con sus ojos." },
    { ref: "Job 31:1", text: "Hice pacto con mis ojos; ¿Cómo, pues, había yo de mirar a una virgen?" },
    { ref: "2 Corintios 7:1", text: "Así que, amados, puesto que tenemos tales promesas, limpiémonos de toda contaminación de carne y de espíritu, perfeccionando la santidad en el temor de Dios." },
    { ref: "Romanos 6:12", text: "No reine, pues, el pecado en vuestro cuerpo mortal, de modo que lo obedezcáis en sus concupiscencias." },
    { ref: "Gálatas 5:19-21", text: "Y manifiestas son las obras de la carne, que son: adulterio, fornicación, inmundicia, lascivia... los que practican tales cosas no heredarán el reino de Dios." },
    { ref: "Efesios 5:5", text: "Porque sabéis esto, que ningún fornicario, o inmundo, o avaro, que es idólatra, tiene herencia en el reino de Cristo y de Dios." },
    { ref: "Tito 2:11-12", text: "Porque la gracia de Dios se ha manifestado para salvación... enseñándonos que, renunciando a la impiedad y a los deseos mundanos, vivamos en este siglo sobria, justa y piadosamente." },
    { ref: "1 Corintios 10:8", text: "Ni forniquemos, como algunos de ellos fornicaron, y cayeron en un día veintitrés mil." },
    { ref: "Romanos 8:13", text: "Porque si vivís conforme a la carne, moriréis; mas si por el Espíritu hacéis morir las obras de la carne, viviréis." },
    { ref: "Mateo 15:19", text: "Porque del corazón salen los malos pensamientos, los homicidios, los adulterios, las fornicaciones, los hurtos, los falsos testimonios, las blasfemias." },
    { ref: "1 Tesalonicenses 4:7", text: "Pues no nos ha llamado Dios a inmundicia, sino a santificación." }
];

// 2. Lista de 30 versículos contra el Orgullo / Soberbia
const orgulloVerses = [
    { ref: "Proverbios 16:18", text: "Antes del quebrantamiento es la soberbia, y antes de la caída la altivez de espíritu." },
    { ref: "Santiago 4:6", text: "Pero él da mayor gracia. Por esto dice: Dios resiste a los soberbios, y da gracia a los humildes." },
    { ref: "1 Pedro 5:5", text: "Igualmente, jóvenes, estad sujetos a los ancianos; y todos, sumisos unos a otros, revestíos de humildad; porque: Dios resiste a los soberbios, y da gracia a los humildes." },
    { ref: "Proverbios 11:2", text: "Cuando viene la soberbia, viene también la deshonra; mas con los humildes está la sabiduría." },
    { ref: "Proverbios 29:23", text: "La soberbia del hombre le abate; pero al humilde de espíritu sustenta la honra." },
    { ref: "Filipenses 2:3", text: "Nada hagáis por contienda o por vanagloria; antes bien con humildad, estimando cada uno a los demás como superiores a él mismo." },
    { ref: "Romanos 12:16", text: "Unánimes entre vosotros; no altivos, sino asociándoos con los humildes. No seáis sabios en vuestra propia opinión." },
    { ref: "Proverbios 8:13", text: "El temor de Jehová es aborrecer el mal; la soberbia y la arrogancia, el mal camino, y la boca perversa, aborrezco." },
    { ref: "Isaías 2:11", text: "La altivez de los ojos del hombre será abatida, y la soberbia de los hombres será humillada; y Jehová solo será exaltado en aquel día." },
    { ref: "Salmos 138:6", text: "Porque Jehová es excelso, y atiende al humilde, mas al altivo mira de lejos." },
    { ref: "1 Juan 2:16", text: "Porque todo lo que hay en el mundo, los deseos de la carne, los deseos de los ojos, y la vanagloria de la vida, no proviene del Padre, sino del mundo." },
    { ref: "Gálatas 6:3", text: "Porque el que se cree ser algo, no siendo nada, a sí mismo se engaña." },
    { ref: "Lucas 14:11", text: "Porque cualquiera que se enaltece, será humillado; y el que se humilla, será enaltecido." },
    { ref: "1 Corintios 4:7", text: "Porque ¿quién te distingue? ¿o qué tienes que no hayas recibido? Y si lo recibiste, ¿por qué te glorías como si no lo hubieras recibido?" },
    { ref: "Proverbios 21:4", text: "Altivez de ojos, y orgullo de corazón, y pensamiento de impíos, son pecado." },
    { ref: "Romanos 11:20", text: "Bien; por su incredulidad fueron desgajadas, pero tú por la fe estás en pie. No te ensoberbezcas, sino teme." },
    { ref: "2 Crónicas 26:16", text: "Mas cuando ya era fuerte, su corazón se enalteció para su ruina; porque se rebeló contra Jehová su Dios..." },
    { ref: "Daniel 4:37", text: "Ahora yo Nabucodonosor alabo, engrandezco y glorifico al Rey del cielo... y él puede humillar a los que andan con soberbia." },
    { ref: "Jeremías 9:23", text: "Así dijo Jehová: No se alabe el sabio en su sabiduría, ni en su valentía se alabe el valiente, ni el rico se alabe en sus riquezas." },
    { ref: "Proverbios 18:12", text: "Antes del quebrantamiento se eleva el corazón del hombre, y antes de la honra es el abatimiento." },
    { ref: "Proverbios 27:2", text: "Alábete el extraño, y no tu propia boca; el ajeno, y no los labios tuyos." },
    { ref: "2 Corintios 10:17", text: "Mas el que se gloría, gloríese en el Señor." },
    { ref: "Sofonías 2:3", text: "Buscad a Jehová todos los humildes de la tierra, los que pusisteis por obra su juicio; buscad justicia, buscad mansedumbre..." },
    { ref: "Romanos 12:3", text: "Digo, pues, por la gracia que me es dada, a cada cual que está entre vosotros, que no tenga más alto concepto de sí que el que debe tener..." },
    { ref: "Colosenses 3:12", text: "Vestíos, pues, como escogidos de Dios, santos y amados, de entrañable misericordia, de benignidad, de humildad, de mansedumbre, de paciencia." },
    { ref: "Efesios 4:2", text: "Con toda humildad y mansedumbre, soportándoos con paciencia los unos a los otros en amor." },
    { ref: "Miqueas 6:8", text: "Oh hombre, él te ha declarado lo que es bueno, y qué pide Jehová de ti: solamente hacer justicia, y amar misericordia, y humillarte ante tu Dios." },
    { ref: "Salmos 10:4", text: "El malo, por la altivez de su rostro, no busca a Dios; no hay Dios en ninguno de sus pensamientos." },
    { ref: "Habacuc 2:4", text: "He aquí que aquel cuya alma no es recta, se enorgullece; mas el justo por su fe vivirá." },
    { ref: "1 Samuel 2:3", text: "No multipliquéis palabras de grandeza y altanería; cesen las palabras arrogantes de vuestra boca, porque el Dios de todo saber es Jehová." }
];

// 3. Lista de 30 versículos contra la Falta de Gratitud
const gratitudVerses = [
    { ref: "1 Tesalonicenses 5:18", text: "Dad gracias en todo, porque esta es la voluntad de Dios para con vosotros en Cristo Jesús." },
    { ref: "Filipenses 2:14", text: "Haced todo sin murmuraciones y contiendas." },
    { ref: "Colosenses 3:15", text: "Y la paz de Dios gobierne en vuestros corazones, a la que asimismo fuisteis llamados en un solo cuerpo; y sed agradecidos." },
    { ref: "Colosenses 3:17", text: "Y todo lo que hacéis, sea de palabra o de hecho, hacedlo todo en el nombre del Señor Jesús, dando gracias a Dios Padre por medio de él." },
    { ref: "Efesios 5:20", text: "Dando siempre gracias por todo al Dios y Padre, en el nombre de nuestro Señor Jesucristo." },
    { ref: "Salmos 103:2", text: "Bendice, alma mía, a Jehová, Y no olvides ninguno de sus beneficios." },
    { ref: "Salmos 107:1", text: "Alabad a Jehová, porque él es bueno; Porque para siempre es su misericordia." },
    { ref: "Salmos 118:24", text: "Este es el día que hizo Jehová; Nos gozaremos y alegraremos en él." },
    { ref: "Hebreos 13:15", text: "Así que, ofrezcamos siempre a Dios, por medio de él, sacrificio de alabanza, es decir, fruto de labios que confiesan su nombre." },
    { ref: "Filipenses 4:6", text: "Por nada estéis afanosos, sino sean conocidas vuestras peticiones delante de Dios en toda oración y ruego, con acción de gracias." },
    { ref: "Santiago 1:17", text: "Toda buena dádiva y todo don perfecto desciende de lo alto, del Padre de las luces, en el cual no hay mudanza, ni sombra de variación." },
    { ref: "1 Crónicas 16:34", text: "Aclamad a Jehová, porque él es bueno; Porque su misericordia es eterna." },
    { ref: "Salmos 9:1", text: "Te alabaré, oh Jehová, con todo mi corazón; Contaré todas tus maravillas." },
    { ref: "Salmos 34:1", text: "Bendeciré a Jehová en todo tiempo; Su alabanza estará de continuo en mi boca." },
    { ref: "Salmos 100:4", text: "Entrad por sus puertas con acción de gracias, Por sus atrios con alabanza; Alabadle, bendecid su nombre." },
    { ref: "Romanos 1:21", text: "Pues habiendo conocido a Dios, no le glorificaron como a Dios, ni le dieron gracias, sino que se envanecieron en sus razonamientos, y su necio corazón fue entenebrecido." },
    { ref: "2 Corintios 9:15", text: "¡Gracias a Dios por su don inefable!" },
    { ref: "Colosenses 2:7", text: "Arraigados y sobreedificados en él, y confirmados en la fe, así como habéis sido enseñados, abundando en acciones de gracias." },
    { ref: "Colosenses 4:2", text: "Perseverad en la oración, velando en ella con acción de gracias." },
    { ref: "1 Timoteo 4:4", text: "Porque todo lo que Dios creó es bueno, y nada es de desecharse, si se toma con acción de gracias." },
    { ref: "Filemón 1:4", text: "Doy gracias a mi Dios, haciendo siempre memoria de ti en mis oraciones." },
    { ref: "Hebreos 12:28", text: "Así que, recibiendo nosotros un reino inconmovible, tengamos gratitud, y mediante ella sirvamos a Dios agradándole con temor y reverencia." },
    { ref: "Salmos 95:2", text: "Lleguemos ante su presencia con alabanza; Aclamémosle con cánticos." },
    { ref: "Salmos 105:1", text: "Alabad a Jehová, invocad su nombre; Dad a conocer sus obras en los pueblos." },
    { ref: "Salmos 111:1", text: "Alabaré a Jehová con todo el corazón, En la compañía y congregación de los rectos." },
    { ref: "Salmos 136:1", text: "Alabad a Jehová, porque él es bueno, Porque para siempre es su misericordia." },
    { ref: "Jonás 2:9", text: "Mas yo con voz de alabanza te ofreceré sacrificios; Pagaré lo que prometí. La salvación es de Jehová." },
    { ref: "Efesios 1:16", text: "No ceso de dar gracias por vosotros, haciendo memoria de vosotros en mis oraciones." },
    { ref: "2 Tesalonicenses 1:3", text: "Debemos siempre dar gracias a Dios por vosotros, hermanos, como es digno, por cuanto vuestra fe va creciendo..." },
    { ref: "Apocalipsis 7:12", text: "Amén. La bendición y la gloria y la sabiduría y la acción de gracias y la honra y el poder y la fortaleza, sean a nuestro Dios por los siglos de los siglos. Amén." }
];